const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const auth=$('#auth'),tool=$('#tool');let reg=false;
function authOpen(r=false){reg=r;auth.classList.add('show');$('#authTitle').textContent=r?'Create your account':'Welcome back';$('#submit').textContent=r?'Create account':'Sign in'}
$('#account').onclick=()=>authOpen(false);$('#create').onclick=()=>authOpen(true);$('.x').onclick=()=>{auth.classList.remove('show');tool.classList.remove('show')};
$('#switch').onclick=()=>authOpen(!reg);
$('#submit').onclick=()=>{let u=$('#user').value.trim(),e=$('#email').value.trim(),p=$('#pass').value;if(u.length<3||p.length<6)return alert('Use a username (3+) and password (6+).');let a=JSON.parse(localStorage.getItem('ilyrx_accounts')||'{}');if(reg){if(a[u])return alert('Username already exists.');a[u]={email:e,password:p};localStorage.setItem('ilyrx_accounts',JSON.stringify(a))}else if(!a[u]||a[u].password!==p)return alert('Invalid username or password.');localStorage.setItem('ilyrx_session',u);$('#account').textContent=u;auth.classList.remove('show')};if(localStorage.getItem('ilyrx_session'))$('#account').textContent=localStorage.getItem('ilyrx_session');
$('#theme').onclick=()=>document.body.classList.toggle('light');
const tools={json:['JSON Formatter',`<textarea id="ta" placeholder='{"name":"IlyrX"}'></textarea><button class="primary" id="go">Format</button><div class="toolout" id="out"></div>`],counter:['Character Counter',`<textarea id="ta" placeholder="Type here..."></textarea><div class="toolout" id="out">Characters: 0 | Words: 0 | Lines: 0</div>`],password:['Password Generator',`<input id="len" type="number" value="18" min="8" max="64"><button class="primary" id="go">Generate</button><div class="toolout" id="out"></div>`],color:['Color Converter',`<input id="ta" value="#7567ff"><button class="primary" id="go">Convert</button><div class="toolout" id="out"></div>`]};
$$('[data-tool]').forEach(b=>b.onclick=()=>{let d=tools[b.dataset.tool];$('#toolTitle').textContent=d[0];$('#toolBody').innerHTML=d[1];tool.classList.add('show');let t=b.dataset.tool;if(t==='json')$('#go').onclick=()=>{try{$('#out').textContent=JSON.stringify(JSON.parse($('#ta').value),null,2)}catch(e){$('#out').textContent='Invalid JSON'}};if(t==='counter')$('#ta').oninput=e=>{let v=e.target.value;$('#out').textContent=`Characters: ${v.length} | Words: ${v.trim()?v.trim().split(/\s+/).length:0} | Lines: ${v?v.split('\n').length:0}`};if(t==='password')$('#go').onclick=()=>{let c='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*',n=Math.max(8,Math.min(64,+$('#len').value||18)),p='';for(let i=0;i<n;i++)p+=c[Math.floor(Math.random()*c.length)];$('#out').textContent=p};if(t==='color')$('#go').onclick=()=>{let h=$('#ta').value.replace('#','');if(!/^[0-9a-f]{6}$/i.test(h))return $('#out').textContent='Use a 6-digit HEX value.';$('#out').textContent=`HEX: #${h.toUpperCase()}\nRGB: rgb(${parseInt(h.slice(0,2),16)}, ${parseInt(h.slice(2,4),16)}, ${parseInt(h.slice(4),16)})`}});
$$('.download').forEach(b=>b.onclick=()=>alert('Demo download. Replace this button with a file URL you are authorized to distribute.'));
$('#search').oninput=e=>{let q=e.target.value.toLowerCase();$$('.downloads article').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'flex':'none')};
